import React from "react"
import { graphql, useStaticQuery } from "gatsby"
import Img from "gatsby-image"

import Layout from "../components/layout"
import SEO from "../components/seo"
import "../components/Styles/portfolio-css-module.css"
// import { getClass } from "../utils/getclass"

const PortfolioPage = () => {
  const data = useStaticQuery(graphql`
    query Images {
      images: allFile(filter: { relativeDirectory: { eq: "gallery" } }) {
        nodes {
          id
          childImageSharp {
            fixed(width: 400) {
              ...GatsbyImageSharpFixed
            }
          }
        }
      }
    }
  `)

  // const images = data.images.nodes.map(image => <Img key={image.id} fixed={image.childImageSharp.fixed} ></Img>)

  return (
    <Layout>
      <SEO title="Portfolio" />
      <main className="photos">
        <Img
          key={data.images.nodes[0].id}
          fixed={data.images.nodes[0].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[1].id}
          fixed={data.images.nodes[1].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[2].id}
          fixed={data.images.nodes[2].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[3].id}
          fixed={data.images.nodes[3].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[4].id}
          fixed={data.images.nodes[4].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[5].id}
          fixed={data.images.nodes[5].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[6].id}
          fixed={data.images.nodes[6].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[7].id}
          fixed={data.images.nodes[7].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[8].id}
          fixed={data.images.nodes[8].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[9].id}
          fixed={data.images.nodes[9].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[10].id}
          fixed={data.images.nodes[10].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[11].id}
          fixed={data.images.nodes[11].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[12].id}
          fixed={data.images.nodes[12].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[13].id}
          fixed={data.images.nodes[13].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[14].id}
          fixed={data.images.nodes[14].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[15].id}
          fixed={data.images.nodes[15].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[16].id}
          fixed={data.images.nodes[16].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[17].id}
          fixed={data.images.nodes[17].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[18].id}
          fixed={data.images.nodes[18].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[19].id}
          fixed={data.images.nodes[19].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[20].id}
          fixed={data.images.nodes[20].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[21].id}
          fixed={data.images.nodes[21].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[22].id}
          fixed={data.images.nodes[22].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[23].id}
          fixed={data.images.nodes[23].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[24].id}
          fixed={data.images.nodes[24].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[25].id}
          fixed={data.images.nodes[25].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[26].id}
          fixed={data.images.nodes[26].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[27].id}
          fixed={data.images.nodes[27].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[28].id}
          fixed={data.images.nodes[28].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[29].id}
          fixed={data.images.nodes[29].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[30].id}
          fixed={data.images.nodes[30].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[31].id}
          fixed={data.images.nodes[31].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[32].id}
          fixed={data.images.nodes[32].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[33].id}
          fixed={data.images.nodes[33].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[34].id}
          fixed={data.images.nodes[34].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[35].id}
          fixed={data.images.nodes[35].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[36].id}
          fixed={data.images.nodes[36].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[37].id}
          fixed={data.images.nodes[37].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[38].id}
          fixed={data.images.nodes[38].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[39].id}
          fixed={data.images.nodes[39].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[40].id}
          fixed={data.images.nodes[40].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[41].id}
          fixed={data.images.nodes[41].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[42].id}
          fixed={data.images.nodes[42].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[43].id}
          fixed={data.images.nodes[43].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[44].id}
          fixed={data.images.nodes[44].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[45].id}
          fixed={data.images.nodes[45].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[46].id}
          fixed={data.images.nodes[46].childImageSharp.fixed}
        ></Img>
        {/* <Img
          key={data.images.nodes[47].id}
          fixed={data.images.nodes[47].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[48].id}
          fixed={data.images.nodes[48].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[49].id}
          fixed={data.images.nodes[49].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[50].id}
          fixed={data.images.nodes[50].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[51].id}
          fixed={data.images.nodes[51].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[52].id}
          fixed={data.images.nodes[52].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[53].id}
          fixed={data.images.nodes[53].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[54].id}
          fixed={data.images.nodes[54].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[55].id}
          fixed={data.images.nodes[55].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[56].id}
          fixed={data.images.nodes[56].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[57].id}
          fixed={data.images.nodes[57].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[58].id}
          fixed={data.images.nodes[58].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[59].id}
          fixed={data.images.nodes[59].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[60].id}
          fixed={data.images.nodes[60].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[61].id}
          fixed={data.images.nodes[61].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[62].id}
          fixed={data.images.nodes[62].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[63].id}
          fixed={data.images.nodes[63].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[64].id}
          fixed={data.images.nodes[64].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[65].id}
          fixed={data.images.nodes[65].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[66].id}
          fixed={data.images.nodes[66].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[67].id}
          fixed={data.images.nodes[67].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[68].id}
          fixed={data.images.nodes[68].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[69].id}
          fixed={data.images.nodes[69].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[70].id}
          fixed={data.images.nodes[70].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[71].id}
          fixed={data.images.nodes[71].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[72].id}
          fixed={data.images.nodes[72].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[73].id}
          fixed={data.images.nodes[73].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[74].id}
          fixed={data.images.nodes[74].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[75].id}
          fixed={data.images.nodes[75].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[76].id}
          fixed={data.images.nodes[76].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[77].id}
          fixed={data.images.nodes[77].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[78].id}
          fixed={data.images.nodes[78].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[79].id}
          fixed={data.images.nodes[79].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[80].id}
          fixed={data.images.nodes[80].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[81].id}
          fixed={data.images.nodes[81].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[82].id}
          fixed={data.images.nodes[82].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[83].id}
          fixed={data.images.nodes[83].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[84].id}
          fixed={data.images.nodes[84].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[85].id}
          fixed={data.images.nodes[85].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[86].id}
          fixed={data.images.nodes[86].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[87].id}
          fixed={data.images.nodes[87].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[88].id}
          fixed={data.images.nodes[88].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[89].id}
          fixed={data.images.nodes[89].childImageSharp.fixed}
        ></Img>
        <Img
          key={data.images.nodes[90].id}
          fixed={data.images.nodes[90].childImageSharp.fixed}
        ></Img> */}
      </main>
    </Layout>
  )
}

export default PortfolioPage
